### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by evertramos**

### CODE REVIEW

**Comment by pathros** [comment]
Hello! Is all of this related to Docker Rootless?

**Comment by evertramos** [comment]
Hello @pathros no Sir. There is a lot of code in this which has nothing to do with rootless, in fact, this repo is appart from any other script, designed to be reused by other scripts. So, not sure what you are using it, but the base script is a reusable packages of scripts that I am building daily.

**Comment by pathros** [comment]
I follow your base script, since I noticed you use part of it for the Docker Nginx automation 👀

**Comment by evertramos** [comment]
Nice @pathros!!! Thanks for the heads up. I use this base script for a couple projects inclusing server-automation that does quiet a few things, besides the nginx proxy. But not all is documented yet. Have you tried the [Server Automation](https://github.com/evertramos/server-automation)? The is many tricks hidden and may more to come. I will document everything and if you like bash as I do, you can look around what functions here (basescript) as usefull and keep track of it and if any update breaks anything let me know or send PR so we can keep as simple as possible each function to abstract the usage for other developers. Thanks again for your support!

**Comment by pathros** [comment]
All right, @evertramos, I will keep on looking around it searching for breaks and enhancements. I find it very useful.

I actually looked at it when I realized these [Server Automation](https://github.com/evertramos/server-automation) scripts are used for the [Nginx Proxy Automation](https://github.com/evertramos/nginx-proxy-automation). 

You know, I forked the latter in order to implement support for Docker Rootless, which I PR'd to you. To achieve that, I had to check out your base scripts.

Best regards!

**Comment by evertramos** [comment]
Oh Hello @pathros! I didn´t did the connection to you, the PR is still open! I will check it all before merging, but thank you in advace for that. I myself use it only in customer's as rootless, in my personal server administration use regular root and other access management for other users. The server automation will integrate the instalation of nginx-proxy as I alredy have at [easy-server](https://github.com/evertramos/easy-server). Also I have putted toguether an API in order to automate most of the published scripts, and some of them I need to rewrite because it was written for an specific customer in last years. So, I will abstract all scripts to run smothly in a single API, even to fire new sites. The API I am still deciding if it will be open sourced, but for now all scripts will be releases as OS. Thanks again and I will look close to rootless as soon as I finish the current workload.

**Comment by pathros** [comment]
All right, @evertramos !!!

**Pull request merged**
